import { ArrowDown, Combine, FileCheck2, Minimize2, PackageOpen } from 'lucide-react';
import { DataNotice, Metric, PageHeader } from '../../components/ui';

export const metadata = { title: 'Cost & Context' };

const mechanisms = [
  { icon: Combine, name: 'Action Fusion', value: '42 → 23', saving: '19 calls avoided', progress: 45, tone: 'blue' },
  { icon: Minimize2, name: 'Online Context Compact', value: '84.1K → 36.8K', saving: '56.2% fewer tokens', progress: 56, tone: 'violet' },
  { icon: PackageOpen, name: 'ObservationPack', value: '31.4K → 9.7K', saving: '69.1% packed', progress: 69, tone: 'cyan' },
  { icon: FileCheck2, name: 'Evidence Reducer', value: '128 → 47', saving: '81 items filtered', progress: 63, tone: 'green' },
];

const contextEvents = [
  { time: '10:42', value: 4200, label: 'Initial context' }, { time: '10:43', value: 8900, label: 'Tool observations' }, { time: '10:44', value: 18400, label: 'Peak context' }, { time: '10:45', value: 7210, label: 'Compacted' }, { time: '10:46', value: 7800, label: 'Current' },
];

export default function ContextPage() { return <div className="page-stack"><PageHeader eyebrow="Efficiency" title="Cost & Context" description="Understand resource consumption and verify exactly how GSS optimization changes each execution." /><DataNotice /><section className="metric-ribbon"><Metric label="Input tokens" value="124.8K" note="Today" /><Metric label="Output tokens" value="18.3K" note="Today" /><Metric label="LLM calls" value="47" note="19 avoided" /><Metric label="Tool calls" value="63" note="42% fused" /><Metric label="Estimated cost" value="$4.82" note="$3.29 saved" trend="down" /></section><div className="context-grid"><section className="panel context-chart"><div className="section-heading"><div><p className="eyebrow">Active execution</p><h2>Context evolution</h2></div><span className="subtle-label">EXE-8421</span></div><div className="context-bars" aria-label="Context size throughout execution">{contextEvents.map(event => <div className="context-bar-item" key={event.time}><div className="bar-label"><span>{event.label}</span><strong>{(event.value / 1000).toFixed(1)}K</strong></div><div className="context-track"><span style={{ width: `${event.value / 184}%` }} /></div><small>{event.time}</small></div>)}</div><div className="compact-callout"><ArrowDown size={18} /><div><strong>Compaction preserved evidence IDs and constraints</strong><p>18.4K → 7.2K tokens while retaining all 12 selected evidence items.</p></div><span>−60.9%</span></div></section><section className="panel spend-panel"><div className="section-heading"><div><p className="eyebrow">Seven-day spend</p><h2>$28.41</h2></div><span className="saving-badge">$19.08 saved</span></div><div className="spend-bars">{[52, 68, 45, 76, 61, 88, 58].map((value, index) => <div key={index}><span style={{ height: `${value}%` }} /><small>{['M','T','W','T','F','S','S'][index]}</small></div>)}</div><div className="spend-legend"><span><i className="legend-dot actual" />Actual</span><span><i className="legend-dot avoided" />Avoided estimate</span></div></section></div><section><div className="section-heading standalone"><div><p className="eyebrow">Optimization mechanisms</p><h2>Where the savings came from</h2></div></div><div className="mechanism-grid">{mechanisms.map(item => <article className={`mechanism-card ${item.tone}`} key={item.name}><span className="mechanism-icon"><item.icon size={18} /></span><div><span>{item.name}</span><strong>{item.value}</strong><small>{item.saving}</small><div className="mechanism-track"><span style={{ width: `${item.progress}%` }} /></div></div></article>)}</div></section></div>; }
