'use client';
import { Activity, Globe2, ShieldAlert } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';

const threatData = [{ name: 'Critical', value: 18, color: '#ff3b30' }, { name: 'High', value: 27, color: '#ff9f0a' }, { name: 'Medium', value: 31, color: '#ffd60a' }, { name: 'Low', value: 24, color: '#34c759' }];
const geoData = [{ region: 'US East', critical: 14, high: 21, medium: 17, low: 9 }, { region: 'EU West', critical: 7, high: 19, medium: 20, low: 12 }, { region: 'AP South', critical: 5, high: 12, medium: 16, low: 19 }, { region: 'SA East', critical: 3, high: 8, medium: 12, low: 13 }];
const initialTraffic = [{ time: '09:12', ingress: 62, egress: 33 }, { time: '09:14', ingress: 74, egress: 38 }, { time: '09:16', ingress: 68, egress: 43 }, { time: '09:18', ingress: 91, egress: 48 }, { time: '09:20', ingress: 84, egress: 44 }, { time: '09:22', ingress: 102, egress: 55 }, { time: '09:24', ingress: 96, egress: 51 }];
const chartTooltip = { contentStyle: { background: 'rgba(255,255,255,.96)', border: '1px solid #e5e5ea', borderRadius: 10, color: '#1d1d1f', boxShadow: '0 10px 30px rgba(0,0,0,.08)' }, itemStyle: { color: '#1d1d1f' }, labelStyle: { color: '#6e6e73' } };

function Heading({ icon, title, subtitle }: { icon: ReactNode; title: string; subtitle: string }) { return <div className="card-heading"><div><h3>{icon}{title}</h3><p>{subtitle}</p></div><span className="subtle-label">Demo</span></div>; }
export default function ChartsGroup() {
  const [traffic, setTraffic] = useState(initialTraffic);
  useEffect(() => { const timer = setInterval(() => setTraffic(previous => { const last = previous[previous.length - 1]; return [...previous.slice(-11), { time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), ingress: Math.max(35, Math.min(125, last.ingress + Math.round(Math.random() * 18 - 9))), egress: Math.max(18, Math.min(75, last.egress + Math.round(Math.random() * 12 - 6))) }]; }), 2600); return () => clearInterval(timer); }, []);
  return <div className="chart-grid"><section className="panel chart-card wide"><Heading icon={<Activity size={16} />} title="Network throughput" subtitle="Simulated traffic · Mbps" /><div className="chart-body"><ResponsiveContainer width="100%" height="100%"><LineChart data={traffic}><CartesianGrid strokeDasharray="3 5" stroke="#ececf0" vertical={false} /><XAxis dataKey="time" stroke="#86868b" fontSize={11} tickLine={false} axisLine={false} /><YAxis stroke="#86868b" fontSize={11} tickLine={false} axisLine={false} /><Tooltip {...chartTooltip} /><Line type="monotone" dataKey="ingress" name="Ingress" stroke="#0071e3" strokeWidth={2.2} dot={false} /><Line type="monotone" dataKey="egress" name="Egress" stroke="#34c759" strokeWidth={2.2} dot={false} /></LineChart></ResponsiveContainer></div></section><section className="panel chart-card"><Heading icon={<ShieldAlert size={16} />} title="Signal mix" subtitle="Simulated severity distribution" /><div className="chart-body donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={threatData} dataKey="value" innerRadius={52} outerRadius={72} paddingAngle={4} stroke="none">{threatData.map(item => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip {...chartTooltip} /></PieChart></ResponsiveContainer><div className="donut-total"><strong>100</strong><span>signals</span></div></div></section><section className="panel chart-card"><Heading icon={<Globe2 size={16} />} title="Regional signals" subtitle="Simulated density by region" /><div className="chart-body"><ResponsiveContainer width="100%" height="100%"><BarChart data={geoData} layout="vertical"><CartesianGrid strokeDasharray="3 5" horizontal={false} stroke="#ececf0" /><XAxis type="number" hide /><YAxis dataKey="region" type="category" stroke="#86868b" fontSize={11} tickLine={false} axisLine={false} width={58} /><Tooltip {...chartTooltip} /><Bar dataKey="critical" stackId="a" fill="#ff3b30" barSize={13} /><Bar dataKey="high" stackId="a" fill="#ff9f0a" /><Bar dataKey="medium" stackId="a" fill="#ffd60a" /><Bar dataKey="low" stackId="a" fill="#34c759" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div></section></div>;
}
