apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: asq_db
    user: asq_user
    secureJsonData:
      password: asq_password
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
    access: proxy
    isDefault: true
    editable: true
