[security]
# Cho phép nhúng panel Grafana vào Iframe hoặc giao diện của BFF Next.js (Standalone)
allow_embedding = true

[auth.anonymous]
# Tuỳ thuộc thiết kế BFF, nếu ẩn danh được phép xem dashboard thì bật true, mặc định false để chặt chẽ.
enabled = false

[panels]
disable_sanitize_html = false
