name: OSV dependency scan

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  push:
    branches: [main]
  schedule:
    - cron: '12 12 * * 1'

jobs:
  scan-full:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@c7c7bcb0773cc4678a674ada03a66cc5c4325476 # v2.6.0
    with:
      scan-args: |-
        --include-git-root
        -r
        ./

  scan-pull-request:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@c7c7bcb0773cc4678a674ada03a66cc5c4325476 # v2.6.0
    with:
      scan-args: |-
        --include-git-root
        -r
        ./
